heat_template_version: 2018-08-31

description: v1.0.0 Template for network

parameters:
  RouterName:
    description: RouterName
    type: string
    default: router

  SubnetCidr1:
    description: SubnetCidr1
    type: string
    default: 10.0.1.0/24
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+/[0-9]+$"

  SubnetCidr2:
    description: SubnetCidr2
    type: string
    default: 172.16.99.0/24
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+/[0-9]+$"

  RouterIp1:
    description: RouterIp
    type: string
    default: 10.0.1.1
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"

  RouterIp2:
    description: RouterIp
    type: string
    default: 172.16.99.1
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"

  PC1Ip:
    description: PC1Ip
    type: string
    default: 10.0.1.10
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"

  PC2Ip:
    description: PC2Ip
    type: string
    default: 172.16.99.20
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"

  PC3Ip:
    description: PC3Ip
    type: string
    default: 172.16.99.30
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"

  SSHKeyName:
    description: SSHKeyName
    type: string

resources:
  ########################
  ### NETWORK & SUBNET ###
  ########################
  Network1:
    type: OS::Neutron::Net
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "network1"]] }
      admin_state_up: True
      shared: False

  Network2:
    type: OS::Neutron::Net
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "network2"]] }
      admin_state_up: True
      shared: False

  Subnet1:
    type: OS::Neutron::Subnet
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "subnet1"]] }
      cidr: { get_param: SubnetCidr1 }
      gateway_ip: { get_param: RouterIp1 }
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      enable_dhcp: True
      network: { get_resource: Network1 }

  Subnet2:
    type: OS::Neutron::Subnet
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "subnet2"]] }
      cidr: { get_param: SubnetCidr2 }
      gateway_ip: { get_param: RouterIp2 }
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      enable_dhcp: True
      network: { get_resource: Network2 }

  ##############
  ### ROUTER ###
  ##############
  RouterPort1:
    type: OS::Neutron::Port
    properties:
      name:
        { list_join: ["-", [{ get_param: "OS::stack_name" }, "router-port1"]] }
      fixed_ips:
        - subnet_id: { get_resource: Subnet1 }
          ip_address: { get_param: RouterIp1 }
      network: { get_resource: Network1 }

  RouterPort2:
    type: OS::Neutron::Port
    properties:
      name:
        { list_join: ["-", [{ get_param: "OS::stack_name" }, "router-port2"]] }
      fixed_ips:
        - subnet_id: { get_resource: Subnet2 }
          ip_address: { get_param: RouterIp2 }
      network: { get_resource: Network2 }

  Router:
    type: OS::Neutron::Router
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "router"]] }
      admin_state_up: True
      external_gateway_info: { network: ext-net }

  RouterInterface1:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: Router }
      port: { get_resource: RouterPort1 }

  RouterInterface2:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: Router }
      port: { get_resource: RouterPort2 }

  #######################
  ### PC1  SEC-group  ###
  #######################
  PC1PrivateSecurityGroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        {
          list_join:
            ["-", [{ get_param: "OS::stack_name" }, "PC1PrivateSecurityGroup"]],
        }
      rules: [
          ### INGRESS RULES
          ## ICMP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: icmp,
            remote_ip_prefix: 0.0.0.0/0,
          },

          ## SSH
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 22,
            port_range_max: 22,
            remote_ip_prefix: 0.0.0.0/0,
          },

          ## RDP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 3389,
            port_range_max: 3389,
            remote_ip_prefix: 0.0.0.0/0,
          },

          {
            direction: ingress,
            ethertype: IPv4,
            protocol: udp,
            port_range_min: 3389,
            port_range_max: 3389,
            remote_ip_prefix: 0.0.0.0/0,
          },

          ## HTTP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 80,
            port_range_max: 80,
            remote_ip_prefix: 158.193.0.0/16,
          },

          ## HTTPS
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 443,
            port_range_max: 443,
            remote_ip_prefix: 158.193.0.0/16,
          },

          ## DNS
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 53,
            port_range_max: 53,
            remote_ip_prefix: 158.193.0.0/16,
          },

          {
            direction: ingress,
            ethertype: IPv4,
            protocol: udp,
            port_range_min: 53,
            port_range_max: 53,
            remote_ip_prefix: 158.193.0.0/16,
          },
          ## VSETKA KOMUNIKACIA Z DRUHEJ SIETE
          {
            direction: ingress,
            ethertype: IPv4,
            remote_ip_prefix: 172.16.99.0/24,
          },
          # Povolenie vsetkeho
          { direction: egress, ethertype: IPv4, remote_ip_prefix: 0.0.0.0/0 },
        ]

  ##############
  ### PC1   ###
  #############

  PC1Port:
    type: OS::Neutron::Port
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "PC1Port"]] }
      security_groups:
        - { get_resource: PC1PrivateSecurityGroup }
      fixed_ips:
        - subnet_id: { get_resource: Subnet1 }
          ip_address: { get_param: PC1Ip }
      network: { get_resource: Network1 }

  PC1Server:
    type: OS::Nova::Server
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "PC1"]] }
      availability_zone: "compute1"
      flavor: "linux"
      image: "cirros"
      key_name: { get_param: SSHKeyName }
      networks:
        - port: { get_resource: PC1Port }
      user_data_format: RAW
      user_data_update_policy: REPLACE
      user_data: |
        #!/bin/bash
        apt-get update -y
        apt-get upgrade -y

  #######################
  ### PC2  SEC-group  ###
  #######################
  PC2PrivateSecurityGroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        {
          list_join:
            ["-", [{ get_param: "OS::stack_name" }, "PC2PrivateSecurityGroup"]],
        }
      rules: [
          ### INGRESS RULES
          ## ICMP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: icmp,
            remote_ip_prefix: 0.0.0.0/0,
          },

          ## SSH
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 22,
            port_range_max: 22,
            remote_ip_prefix: 0.0.0.0/0,
          },

          ## RDP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 3389,
            port_range_max: 3389,
            remote_ip_prefix: 0.0.0.0/0,
          },

          {
            direction: ingress,
            ethertype: IPv4,
            protocol: udp,
            port_range_min: 3389,
            port_range_max: 3389,
            remote_ip_prefix: 0.0.0.0/0,
          },

          ## HTTP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 80,
            port_range_max: 80,
            remote_ip_prefix: 158.193.0.0/16,
          },

          ## HTTPS
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 443,
            port_range_max: 443,
            remote_ip_prefix: 158.193.0.0/16,
          },

          ## DNS
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 53,
            port_range_max: 53,
            remote_ip_prefix: 158.193.0.0/16,
          },

          {
            direction: ingress,
            ethertype: IPv4,
            protocol: udp,
            port_range_min: 53,
            port_range_max: 53,
            remote_ip_prefix: 158.193.0.0/16,
          },
          ## VSETKA KOMUNIKACIA Z DRUHEJ SIETE
          {
            direction: ingress,
            ethertype: IPv4,
            remote_ip_prefix: 10.0.1.0/24,
          },
          # Povolenie vsetkeho
          { direction: egress, ethertype: IPv4, remote_ip_prefix: 0.0.0.0/0 },
        ]

  ##############
  ### PC2   ###
  #############

  PC2Port:
    type: OS::Neutron::Port
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "PC2Port"]] }
      security_groups:
        - { get_resource: PC2PrivateSecurityGroup }
      fixed_ips:
        - subnet_id: { get_resource: Subnet2 }
          ip_address: { get_param: PC2Ip }
      network: { get_resource: Network2 }

  PC2Server:
    type: OS::Nova::Server
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "PC2"]] }
      availability_zone: "compute1"
      flavor: "linux"
      image: "cirros"
      key_name: { get_param: SSHKeyName }
      networks:
        - port: { get_resource: PC2Port }
      user_data_format: RAW
      user_data_update_policy: REPLACE
      user_data: |
        #!/bin/bash
        apt-get update -y
        apt-get upgrade -y

  #######################
  ### PC3  SEC-group  ###
  #######################
  PC3PrivateSecurityGroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        {
          list_join:
            ["-", [{ get_param: "OS::stack_name" }, "PC3PrivateSecurityGroup"]],
        }
      rules: [
          ### INGRESS RULES
          ## ICMP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: icmp,
            remote_ip_prefix: 0.0.0.0/0,
          },

          ## SSH
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 22,
            port_range_max: 22,
            remote_ip_prefix: 0.0.0.0/0,
          },

          ## RDP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 3389,
            port_range_max: 3389,
            remote_ip_prefix: 0.0.0.0/0,
          },

          {
            direction: ingress,
            ethertype: IPv4,
            protocol: udp,
            port_range_min: 3389,
            port_range_max: 3389,
            remote_ip_prefix: 0.0.0.0/0,
          },

          ## HTTP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 80,
            port_range_max: 80,
            remote_ip_prefix: 158.193.0.0/16,
          },

          ## HTTPS
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 443,
            port_range_max: 443,
            remote_ip_prefix: 158.193.0.0/16,
          },

          ## DNS
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 53,
            port_range_max: 53,
            remote_ip_prefix: 158.193.0.0/16,
          },

          {
            direction: ingress,
            ethertype: IPv4,
            protocol: udp,
            port_range_min: 53,
            port_range_max: 53,
            remote_ip_prefix: 158.193.0.0/16,
          },
          ## VSETKA KOMUNIKACIA Z DRUHEJ SIETE
          {
            direction: ingress,
            ethertype: IPv4,
            remote_ip_prefix: 10.0.1.0/24,
          },
          # Povolenie vsetkeho
          { direction: egress, ethertype: IPv4, remote_ip_prefix: 0.0.0.0/0 },
        ]

  ##############
  ### PC3   ###
  #############

  PC3Port:
    type: OS::Neutron::Port
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "PC3Port"]] }
      security_groups:
        - { get_resource: PC3PrivateSecurityGroup }
      fixed_ips:
        - subnet_id: { get_resource: Subnet2 }
          ip_address: { get_param: PC3Ip }
      network: { get_resource: Network2 }

  PC3Server:
    type: OS::Nova::Server
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "PC3"]] }
      availability_zone: "compute1"
      flavor: "linux"
      image: "cirros"
      key_name: { get_param: SSHKeyName }
      networks:
        - port: { get_resource: PC3Port }
      user_data_format: RAW
      user_data_update_policy: REPLACE
      user_data: |
        #!/bin/bash
        apt-get update -y
        apt-get upgrade -y
