heat_template_version: 2018-08-31

description: v1.0.0 Template for network

parameters:
  RouterName:
    description: RouterName
    type: string
    default: router

  SubnetCidr1:
    description: SubnetCidr1
    type: string
    default: 192.168.33.0/24
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+/[0-9]+$"

  SubnetCidr2:
    description: SubnetCidr2
    type: string
    default: 192.168.35.0/24
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+/[0-9]+$"

  RouterIp1:
    description: RouterIp1
    type: string
    default: 192.168.33.1
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"

  RouterIp2:
    description: RouterIp2
    type: string
    default: 192.168.35.1
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"

  PC1Ip:
    description: PC1Ip
    type: string
    default: 192.168.33.10
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"
  PC2Ip:
    description: PC2Ip
    type: string
    default: 192.168.35.10
    constraints:
      - allowed_pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"

  SSHKeyName:
    description: SSHKeyName
    type: string

resources:
  ########################
  ### NETWORK & SUBNET ###
  ########################
  Network:
    type: OS::Neutron::Net
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "network"]] }
      admin_state_up: True
      shared: False

  Subnet1:
    type: OS::Neutron::Subnet
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "subnet1"]] }
      cidr: { get_param: SubnetCidr1 }
      gateway_ip: { get_param: RouterIp1 }
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      enable_dhcp: True
      network: { get_resource: Network }

  Subnet2:
    type: OS::Neutron::Subnet
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "subnet2"]] }
      cidr: { get_param: SubnetCidr2 }
      gateway_ip: { get_param: RouterIp2 }
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      enable_dhcp: True
      network: { get_resource: Network }

  ##############
  ### ROUTER ###
  ##############
  RouterPort1:
    type: OS::Neutron::Port
    properties:
      name:
        { list_join: ["-", [{ get_param: "OS::stack_name" }, "router-port1"]] }
      fixed_ips:
        - subnet_id: { get_resource: Subnet1 }
          ip_address: { get_param: RouterIp1 }
      network: { get_resource: Network }

  RouterPort2:
    type: OS::Neutron::Port
    properties:
      name:
        { list_join: ["-", [{ get_param: "OS::stack_name" }, "router-port2"]] }
      fixed_ips:
        - subnet_id: { get_resource: Subnet2 }
          ip_address: { get_param: RouterIp2 }
      network: { get_resource: Network }

  Router:
    type: OS::Neutron::Router
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "router"]] }
      admin_state_up: True
      external_gateway_info: { network: ext-net }

  RouterInterface1:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: Router }
      port: { get_resource: RouterPort1 }

  RouterInterface2:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: Router }
      port: { get_resource: RouterPort2 }

  ###################
  ### PC 1 ###
  ###################
  PC1PrivateSecurityGroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        {
          list_join:
            ["-", [{ get_param: "OS::stack_name" }, "PC1PrivateSecurityGroup"]],
        }
      rules: [
          ### INGRESS RULES
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 22,
            port_range_max: 22,
            remote_ip_prefix: 0.0.0.0/0,
          },
          ## ICMP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: icmp,
            remote_ip_prefix: 0.0.0.0/0,
          },
          ## FTP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 20,
            port_range_max: 21,
            remote_ip_prefix: 0.0.0.0/0,
          },
          ## medzi sietami
          {
            direction: ingress,
            ethertype: IPv4,
            remote_ip_prefix: 192.168.33.0/24,
          },
          ### EGRESS RULES
          # Povolenie icmp out
          {
            direction: egress,
            ethertype: IPv4,
            protocol: icmp,
            remote_ip_prefix: 0.0.0.0/0,
          },
          # Povolenie vsetkeho
          { direction: egress, ethertype: IPv4, remote_ip_prefix: 0.0.0.0/0 },
        ]

  PC1Port:
    type: OS::Neutron::Port
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "PC1Port"]] }
      security_groups:
        - { get_resource: PC1PrivateSecurityGroup }
      fixed_ips:
        - subnet_id: { get_resource: Subnet1 }
          ip_address: { get_param: PC1Ip }
      network: { get_resource: Network }

  PC1Server:
    type: OS::Nova::Server
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "PC1"]] }
      availability_zone: "compute1"
      flavor: "linux"
      image: "cirros"
      key_name: { get_param: SSHKeyName }
      networks:
        - port: { get_resource: PC1Port }
      user_data_format: RAW
      user_data_update_policy: REPLACE
      user_data: |
        #!/bin/bash
        apt-get update -y
        apt-get upgrade -y
  #############
  ### PC2   ###
  #############
  PC2PrivateSecurityGroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        {
          list_join:
            ["-", [{ get_param: "OS::stack_name" }, "PC2PrivateSecurityGroup"]],
        }
      rules: [
          ### INGRESS RULES

          ## SSH
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 22,
            port_range_max: 22,
            remote_ip_prefix: 0.0.0.0/0,
          },

          ## ICMP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: icmp,
            remote_ip_prefix: 0.0.0.0/0,
          },
          ## FTP
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 20,
            port_range_max: 21,
            remote_ip_prefix: 0.0.0.0/0,
          },
          ## https
          {
            direction: ingress,
            ethertype: IPv4,
            protocol: tcp,
            port_range_min: 443,
            port_range_max: 443,
            remote_ip_prefix: 0.0.0.0/0,
          },

          {
            direction: ingress,
            ethertype: IPv4,
            protocol: udp,
            port_range_min: 443,
            port_range_max: 443,
            remote_ip_prefix: 0.0.0.0/0,
          },
          ### EGRESS RULES
          # Povolenie icmp out
          {
            direction: egress,
            ethertype: IPv4,
            protocol: icmp,
            remote_ip_prefix: 0.0.0.0/0,
          },
          # Povolenie vsetkeho
          { direction: egress, ethertype: IPv4, remote_ip_prefix: 0.0.0.0/0 },
        ]

  PC2Port:
    type: OS::Neutron::Port
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "PC2Port"]] }
      security_groups:
        - { get_resource: PC2PrivateSecurityGroup }
      fixed_ips:
        - subnet_id: { get_resource: Subnet2 }
          ip_address: { get_param: PC2Ip }
      network: { get_resource: Network }

  PC2Server:
    type: OS::Nova::Server
    properties:
      name: { list_join: ["-", [{ get_param: "OS::stack_name" }, "PC2"]] }
      availability_zone: "compute1"
      flavor: "linux"
      image: "cirros"
      key_name: { get_param: SSHKeyName }
      networks:
        - port: { get_resource: PC2Port }
      user_data_format: RAW
      user_data_update_policy: REPLACE
      user_data: |
        #!/bin/bash
        apt-get update -y
        apt-get upgrade -y
